<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../update.Infrastructure/update.Infrastructure.csproj" />
    <ProjectReference Include="../update.Application/update.Application.csproj" />
  </ItemGroup>
</Project>
