using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using update.Domain.Entities;
using update.Domain.Interfaces;
using update.Infrastructure.Data;
using update.Infrastructure.Repositories;
namespace update.Infrastructure;

/// <summary>Registro explícito de repositorios y contexto, sin reflexión ni paquetes auxiliares.</summary>
public static class DependencyInjection
{
    public static IServiceCollection AgregarInfraestructura(this IServiceCollection servicios, string cadenaConexion)
    {
        servicios.AddDbContext<ApplicationDbContext>(opciones => opciones.UseNpgsql(cadenaConexion));
        servicios.AddScoped<IArchivoRepository, ArchivoRepository>();
        servicios.AddScoped<IRepository<Archivo>>(sp => sp.GetRequiredService<IArchivoRepository>());
        servicios.AddScoped<IBloqueoRepository, BloqueoRepository>();
        servicios.AddScoped<IRepository<Bloqueo>>(sp => sp.GetRequiredService<IBloqueoRepository>());
        servicios.AddScoped<ICategoriaRepository, CategoriaRepository>();
        servicios.AddScoped<IRepository<Categoria>>(sp => sp.GetRequiredService<ICategoriaRepository>());
        servicios.AddScoped<ICiudadRepository, CiudadRepository>();
        servicios.AddScoped<IRepository<Ciudad>>(sp => sp.GetRequiredService<ICiudadRepository>());
        servicios.AddScoped<IComentarioRepository, ComentarioRepository>();
        servicios.AddScoped<IRepository<Comentario>>(sp => sp.GetRequiredService<IComentarioRepository>());
        servicios.AddScoped<IConversacionRepository, ConversacionRepository>();
        servicios.AddScoped<IRepository<Conversacion>>(sp => sp.GetRequiredService<IConversacionRepository>());
        servicios.AddScoped<ICotizacionItemRepository, CotizacionItemRepository>();
        servicios.AddScoped<IRepository<CotizacionItem>>(sp => sp.GetRequiredService<ICotizacionItemRepository>());
        servicios.AddScoped<ICotizacionRepository, CotizacionRepository>();
        servicios.AddScoped<IRepository<Cotizacion>>(sp => sp.GetRequiredService<ICotizacionRepository>());
        servicios.AddScoped<IDepartamentoRepository, DepartamentoRepository>();
        servicios.AddScoped<IRepository<Departamento>>(sp => sp.GetRequiredService<IDepartamentoRepository>());
        servicios.AddScoped<IDocumentoVerificacionRepository, DocumentoVerificacionRepository>();
        servicios.AddScoped<IRepository<DocumentoVerificacion>>(sp => sp.GetRequiredService<IDocumentoVerificacionRepository>());
        servicios.AddScoped<IEmprendimientoRepository, EmprendimientoRepository>();
        servicios.AddScoped<IRepository<Emprendimiento>>(sp => sp.GetRequiredService<IEmprendimientoRepository>());
        servicios.AddScoped<IEnlaceEmprendimientoRepository, EnlaceEmprendimientoRepository>();
        servicios.AddScoped<IRepository<EnlaceEmprendimiento>>(sp => sp.GetRequiredService<IEnlaceEmprendimientoRepository>());
        servicios.AddScoped<IEtiquetaRepository, EtiquetaRepository>();
        servicios.AddScoped<IRepository<Etiqueta>>(sp => sp.GetRequiredService<IEtiquetaRepository>());
        servicios.AddScoped<IGuardadoRepository, GuardadoRepository>();
        servicios.AddScoped<IRepository<Guardado>>(sp => sp.GetRequiredService<IGuardadoRepository>());
        servicios.AddScoped<IHistorialSolicitudRepository, HistorialSolicitudRepository>();
        servicios.AddScoped<IRepository<HistorialSolicitud>>(sp => sp.GetRequiredService<IHistorialSolicitudRepository>());
        servicios.AddScoped<IInteresUsuarioRepository, InteresUsuarioRepository>();
        servicios.AddScoped<IRepository<InteresUsuario>>(sp => sp.GetRequiredService<IInteresUsuarioRepository>());
        servicios.AddScoped<IMencionRepository, MencionRepository>();
        servicios.AddScoped<IRepository<Mencion>>(sp => sp.GetRequiredService<IMencionRepository>());
        servicios.AddScoped<IMensajeRepository, MensajeRepository>();
        servicios.AddScoped<IRepository<Mensaje>>(sp => sp.GetRequiredService<IMensajeRepository>());
        servicios.AddScoped<IMensajeAdjuntoRepository, MensajeAdjuntoRepository>();
        servicios.AddScoped<IRepository<MensajeAdjunto>>(sp => sp.GetRequiredService<IMensajeAdjuntoRepository>());
        servicios.AddScoped<IMiembroEmprendimientoRepository, MiembroEmprendimientoRepository>();
        servicios.AddScoped<IRepository<MiembroEmprendimiento>>(sp => sp.GetRequiredService<IMiembroEmprendimientoRepository>());
        servicios.AddScoped<IMonedaRepository, MonedaRepository>();
        servicios.AddScoped<IRepository<Moneda>>(sp => sp.GetRequiredService<IMonedaRepository>());
        servicios.AddScoped<IMotivoReporteRepository, MotivoReporteRepository>();
        servicios.AddScoped<IRepository<MotivoReporte>>(sp => sp.GetRequiredService<IMotivoReporteRepository>());
        servicios.AddScoped<INotificacionRepository, NotificacionRepository>();
        servicios.AddScoped<IRepository<Notificacion>>(sp => sp.GetRequiredService<INotificacionRepository>());
        servicios.AddScoped<IOfertaMentoriaRepository, OfertaMentoriaRepository>();
        servicios.AddScoped<IRepository<OfertaMentoria>>(sp => sp.GetRequiredService<IOfertaMentoriaRepository>());
        servicios.AddScoped<IOportunidadRepository, OportunidadRepository>();
        servicios.AddScoped<IRepository<Oportunidad>>(sp => sp.GetRequiredService<IOportunidadRepository>());
        servicios.AddScoped<IPaisRepository, PaisRepository>();
        servicios.AddScoped<IRepository<Pais>>(sp => sp.GetRequiredService<IPaisRepository>());
        servicios.AddScoped<IParticipanteRepository, ParticipanteRepository>();
        servicios.AddScoped<IRepository<Participante>>(sp => sp.GetRequiredService<IParticipanteRepository>());
        servicios.AddScoped<IPerfilRepository, PerfilRepository>();
        servicios.AddScoped<IRepository<Perfil>>(sp => sp.GetRequiredService<IPerfilRepository>());
        servicios.AddScoped<IPermisoRolRepository, PermisoRolRepository>();
        servicios.AddScoped<IRepository<PermisoRol>>(sp => sp.GetRequiredService<IPermisoRolRepository>());
        servicios.AddScoped<IPostulacionRepository, PostulacionRepository>();
        servicios.AddScoped<IRepository<Postulacion>>(sp => sp.GetRequiredService<IPostulacionRepository>());
        servicios.AddScoped<IProductoRepository, ProductoRepository>();
        servicios.AddScoped<IRepository<Producto>>(sp => sp.GetRequiredService<IProductoRepository>());
        servicios.AddScoped<IProductoArchivoRepository, ProductoArchivoRepository>();
        servicios.AddScoped<IRepository<ProductoArchivo>>(sp => sp.GetRequiredService<IProductoArchivoRepository>());
        servicios.AddScoped<IProductoEtiquetaRepository, ProductoEtiquetaRepository>();
        servicios.AddScoped<IRepository<ProductoEtiqueta>>(sp => sp.GetRequiredService<IProductoEtiquetaRepository>());
        servicios.AddScoped<IPublicacionRepository, PublicacionRepository>();
        servicios.AddScoped<IRepository<Publicacion>>(sp => sp.GetRequiredService<IPublicacionRepository>());
        servicios.AddScoped<IPublicacionArchivoRepository, PublicacionArchivoRepository>();
        servicios.AddScoped<IRepository<PublicacionArchivo>>(sp => sp.GetRequiredService<IPublicacionArchivoRepository>());
        servicios.AddScoped<IPublicacionEtiquetaRepository, PublicacionEtiquetaRepository>();
        servicios.AddScoped<IRepository<PublicacionEtiqueta>>(sp => sp.GetRequiredService<IPublicacionEtiquetaRepository>());
        servicios.AddScoped<IReaccionComentarioRepository, ReaccionComentarioRepository>();
        servicios.AddScoped<IRepository<ReaccionComentario>>(sp => sp.GetRequiredService<IReaccionComentarioRepository>());
        servicios.AddScoped<IReaccionPublicacionRepository, ReaccionPublicacionRepository>();
        servicios.AddScoped<IRepository<ReaccionPublicacion>>(sp => sp.GetRequiredService<IReaccionPublicacionRepository>());
        servicios.AddScoped<IReporteRepository, ReporteRepository>();
        servicios.AddScoped<IRepository<Reporte>>(sp => sp.GetRequiredService<IReporteRepository>());
        servicios.AddScoped<IResenaRepository, ResenaRepository>();
        servicios.AddScoped<IRepository<Resena>>(sp => sp.GetRequiredService<IResenaRepository>());
        servicios.AddScoped<IResenaArchivoRepository, ResenaArchivoRepository>();
        servicios.AddScoped<IRepository<ResenaArchivo>>(sp => sp.GetRequiredService<IResenaArchivoRepository>());
        servicios.AddScoped<ISeguimientoRepository, SeguimientoRepository>();
        servicios.AddScoped<IRepository<Seguimiento>>(sp => sp.GetRequiredService<ISeguimientoRepository>());
        servicios.AddScoped<ISesionRepository, SesionRepository>();
        servicios.AddScoped<IRepository<Sesion>>(sp => sp.GetRequiredService<ISesionRepository>());
        servicios.AddScoped<ISolicitudItemRepository, SolicitudItemRepository>();
        servicios.AddScoped<IRepository<SolicitudItem>>(sp => sp.GetRequiredService<ISolicitudItemRepository>());
        servicios.AddScoped<ISolicitudCotizacionRepository, SolicitudCotizacionRepository>();
        servicios.AddScoped<IRepository<SolicitudCotizacion>>(sp => sp.GetRequiredService<ISolicitudCotizacionRepository>());
        servicios.AddScoped<ISolicitudMentoriaRepository, SolicitudMentoriaRepository>();
        servicios.AddScoped<IRepository<SolicitudMentoria>>(sp => sp.GetRequiredService<ISolicitudMentoriaRepository>());
        servicios.AddScoped<ITipoOportunidadRepository, TipoOportunidadRepository>();
        servicios.AddScoped<IRepository<TipoOportunidad>>(sp => sp.GetRequiredService<ITipoOportunidadRepository>());
        servicios.AddScoped<ITipoPersonaRepository, TipoPersonaRepository>();
        servicios.AddScoped<IRepository<TipoPersona>>(sp => sp.GetRequiredService<ITipoPersonaRepository>());
        servicios.AddScoped<ITipoPublicacionRepository, TipoPublicacionRepository>();
        servicios.AddScoped<IRepository<TipoPublicacion>>(sp => sp.GetRequiredService<ITipoPublicacionRepository>());
        servicios.AddScoped<ITipoReaccionRepository, TipoReaccionRepository>();
        servicios.AddScoped<IRepository<TipoReaccion>>(sp => sp.GetRequiredService<ITipoReaccionRepository>());
        servicios.AddScoped<ITokenRecuperacionRepository, TokenRecuperacionRepository>();
        servicios.AddScoped<IRepository<TokenRecuperacion>>(sp => sp.GetRequiredService<ITokenRecuperacionRepository>());
        servicios.AddScoped<IUsuarioTipoPersonaRepository, UsuarioTipoPersonaRepository>();
        servicios.AddScoped<IRepository<UsuarioTipoPersona>>(sp => sp.GetRequiredService<IUsuarioTipoPersonaRepository>());
        servicios.AddScoped<IUsuarioRepository, UsuarioRepository>();
        servicios.AddScoped<IRepository<Usuario>>(sp => sp.GetRequiredService<IUsuarioRepository>());
        servicios.AddScoped<IUsuarioReservadoRepository, UsuarioReservadoRepository>();
        servicios.AddScoped<IRepository<UsuarioReservado>>(sp => sp.GetRequiredService<IUsuarioReservadoRepository>());
        servicios.AddScoped<IVarianteArchivoRepository, VarianteArchivoRepository>();
        servicios.AddScoped<IRepository<VarianteArchivo>>(sp => sp.GetRequiredService<IVarianteArchivoRepository>());
        servicios.AddScoped<IVerificacionRepository, VerificacionRepository>();
        servicios.AddScoped<IRepository<Verificacion>>(sp => sp.GetRequiredService<IVerificacionRepository>());
        return servicios;
    }
}
